<?php
// $Id: simpletest_switch.module,v 1.1.2.2 2009/11/10 03:20:51 boombatower Exp $

/**
 * @file
 * Provides an easy method to switch between 1.x and 2.x testing APIs.
 */

/**
 * Implement hook_menu().
 */
function simpletest_switch_menu() {
  $items = array();

  $items['admin/config/development/testing/switch'] = array(
    'title callback' => 'simpletest_switch_title',
    'page callback' => 'simpletest_switch_invoke',
    'page arguments' => array(TRUE),
    'access arguments' => array('administer unit tests'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  $items['admin/config/development/testing/switch-second'] = array(
    'page callback' => 'simpletest_switch_invoke',
    'access arguments' => array('administer unit tests'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Get the current testing API version.
 *
 * @return Current testing API version, either: '1.x' or '2.x'.
 */
function simpletest_switch_current() {
  return variable_get('testing_api', '2.x');
}

/**
 * Get the switch callback title.
 *
 * @return unknown
 */
function simpletest_switch_title() {
  return t('Switch to @version', array('@version' => simpletest_switch_current() == '2.x' ? '1.x' : '2.x'));
}

/**
 * Clear Drupal caches and change active testing API version.
 *
 * Due to the complexity of the switch this function must be called twice. The
 * first time simply to change the testing API version and the second to
 * complete the switch.
 *
 * @param boolean $switch Switch the active testing API version.
 */
function simpletest_switch_invoke($switch = FALSE) {
  // If specified switch test API version.
  if ($switch) {
    variable_set('testing_api', simpletest_switch_current() == '2.x' ? '1.x' : '2.x');
  }

  // Use the built in system form to ensure that any addon modules are cleared.
  module_load_include('admin.inc', 'system');
  $form_state = array();
  $form_state['values'] = array('op' => t('Clear all caches'));
  drupal_form_submit('system_performance_settings', $form_state);

  // Hide the cache clearing messages.
  drupal_get_messages();

  // Last iteration so add a display message.
  if (!$switch) {
    drupal_set_message(t('Testing API switched to @version.', array('@version' => simpletest_switch_current())));
  }

  // First time: goto second menu callback, second time: goto testing list.
  drupal_goto($switch ? 'admin/config/development/testing/switch-second': 'admin/config/development/testing');
}

/**
 * Implement hook_registry_files_alter().
 */
function simpletest_switch_registry_files_alter(&$files, $modules) {
  if (simpletest_switch_current() == '1.x') {
    foreach ($files as $key => $file) {
      $key_new = preg_replace('/.*?\/simpletest\//', 'modules/simpletest/', $key);

      // If the string replace had an effect then remove the old file and copy
      // its definition to the new key.
      if ($key_new != $key) {
        if (file_exists($key_new)) {
          $files[$key_new] = $file;
        }
        unset($files[$key]);
      }
    }

    // Remove 2.x compatible test files.
    foreach ($modules as $module) {
      if (!empty($module->info['files'])) {
        if (!empty($module->info['testing_api']) && $module->info['testing_api'] == '2.x') {
          $dir = $module->dir;
          foreach ($module->info['files'] as $file) {
            if (substr($file, -5) == '.test') {
              unset($files["$dir/$file"]);
            }
          }
        }
      }
    }
  }
}

/**
 * Implement hook_system_modules_alter().
 */
function simpletest_switch_system_modules_alter(&$modules) {
  if (simpletest_switch_current() == '1.x') {
    $modules['simpletest']->uri = 'modules/simpletest/simpletest.module';
  }
}
